services:
  db:
    image: postgres:15.3-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: stock_etl_tool
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "9091:5432"

volumes:
  db-data: