server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://zeabur-gcp-asia-east1-1.clusters.zeabur.com:31365/stock_etl_tool
    username: root
    password: 82Tv94G6u3Cy
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    user: root
    password: 82Tv94G6u3Cy
    url: jdbc:postgresql://zeabur-gcp-asia-east1-1.clusters.zeabur.com:31365/stock_etl_tool
    enabled: true


